### ISSUE TITLE
Scrubbing/seeking using keyboard shortcuts exits fullscreen

### ISSUE THREAD

**Issue by Outlet7493** [Materialious/Materialious#876]
**Describe the bug**
Hello,

The player exits fullscreen when seeking using J, K, left, and right arrow. This occurs on at least LibreWolf 137.0-3.

I couldn't find any open issue for this so apologies if I missed it.

Thanks in advance!

**To Reproduce**
1. Open video
2. Enter fullscreen
3. Seek using J, K or left/right arrow
4. Video exists fullscreen

**Expected behavior**
Video stays in fullscreen.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: LibreWolf
 - Version: 137.0-3

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by WardPearce** [comment]
Appears to be a Firefox engine specific issue, I will investigate

**Comment by WardPearce** [comment]
@Outlet7493 I've implemented a fix for this but am unable to test it due to not running a Invidious instance myself (what isn't blocked) so please let me know if `1.8.8` resolves this issue.

**Comment by Outlet7493** [comment]
Hey,

Thank you! However, unfortunately it is still occurring. 😦 

Same setup as initially reported. It also occurs whenever the video buffers, if that helps.
